In [76]:
import numpy as np
import pandas as pd 
import pickle
from sklearn.metrics import f1_score
from catboost import CatBoostClassifier

In [29]:
pip install catboost

Collecting catboost
  Downloading https://files.pythonhosted.org/packages/96/3b/bb419654adcf7efff42ed8a3f84e50c8f236424b7ed1cc8ccd290852e003/catboost-0.24.4-cp37-none-manylinux1_x86_64.whl (65.7MB)
     |████████████████████████████████| 65.7MB 52kB/s
Requirement already satisfied: graphviz in /usr/local/lib/python3.7/dist-packages (from catboost) (0.10.1)
Requirement already satisfied: pandas>=0.24.0 in /usr/local/lib/python3.7/dist-packages (from catboost) (1.1.5)
Requirement already satisfied: numpy>=1.16.0 in /usr/local/lib/python3.7/dist-packages (from catboost) (1.19.5)
Requirement already satisfied: scipy in /usr/local/lib/python3.7/dist-packages (from catboost) (1.4.1)
Requirement already satisfied: matplotlib in /usr/local/lib/python3.7/dist-packages (from catboost) (3.2.2)
Requirement already satisfied: six in /usr/local/lib/python3.7/dist-packages (from catboost) (1.15.0)
Requirement already satisfied: plotly in /usr/local/lib/python3.7/dist-packages (from catboost) (4.4.1)
Requirement already satisfied: pytz>=2017.2 in /usr/local/lib/python3.7/dist-packages (from pandas>=0.24.0->catboost) (2018.9)
Requirement already satisfied: python-dateutil>=2.7.3 in /usr/local/lib/python3.7/dist-packages (from pandas>=0.24.0->catboost) (2.8.1)
Requirement already satisfied: pyparsing!=2.0.4,!=2.1.2,!=2.1.6,>=2.0.1 in /usr/local/lib/python3.7/dist-packages (from matplotlib->catboost) (2.4.7)
Requirement already satisfied: kiwisolver>=1.0.1 in /usr/local/lib/python3.7/dist-packages (from matplotlib->catboost) (1.3.1)
Requirement already satisfied: cycler>=0.10 in /usr/local/lib/python3.7/dist-packages (from matplotlib->catboost) (0.10.0)
Requirement already satisfied: retrying>=1.3.3 in /usr/local/lib/python3.7/dist-packages (from plotly->catboost) (1.3.3)
Installing collected packages: catboost
Successfully installed catboost-0.24.4

In [134]:
def function1(list_order_id):
  '''
  This function take list of order_id as input and return prediction on each order_id
  '''
  if isinstance(list_order_id, list):

      data_train=pickle.load(open('/content/drive/MyDrive/instcart/DATA2/data_train.pkl','rb'))
      data_test =pickle.load(open('/content/drive/MyDrive/instcart/DATA2/data_test.pkl','rb'))
      a=list(data_train.order_id.unique())
      b=list(data_test.order_id.unique())   #order_id in test data
      a.extend(b)
      
      d = dict()   
      # d contains order_id as key and values are predicted product_ids
      
      try:
          for i in range(len(list_order_id)):
              list_order_id[i]=int(list_order_id[i])
      except:
        new_list=[]
        for value in list_order_id:
          try:
            new_list.append(int(value))
          except:
            print('order_id =',value,'not valid.')  
        list_order_id=new_list

      for id in list_order_id:
        if  id  not in a:
          print("order_id=",id,'not present')
          d[id]='This order_id not present'
        else:
        
          model=pickle.load(open("/content/drive/MyDrive/instcart/DATA2/cat_clf_set2",'rb'))
          if id in b:
            features=data_test[data_test.order_id==id]
            y_hat=model.predict(features.drop(['eval_set', 'order_id'], axis=1) )
            features['prediction']=y_hat
            features=features.reset_index()
            output_results=features[['order_id','product_id','prediction']]
          
          else:
            features=data_train[data_train.order_id==id] 
            y_hat=model.predict(features.drop(['eval_set', 'order_id','reordered'], axis=1) )
            features['prediction']=y_hat
            features=features.reset_index()
            output_results=data1[data1.prediction==1]
            
          
          for row in output_results.itertuples():
                if row.prediction== 1:
                    try:
                        d[row.order_id] += ' ' + str(row.product_id)
                    except:
                        d[row.order_id] = str(row.product_id)

          if id not in d:
                  d[id] = 'None'

      sub_csv = pd.DataFrame.from_dict(d, orient='index')
      #Specify orient='index' to create the DataFrame using dictionary keys as rows
      #Reset index
      sub_csv.reset_index(inplace=True)
      #Set column names
      sub_csv.columns = ['order_id', 'products']
      return sub_csv
  else:
      print('enter list of order_id')

In [138]:
#boundary_case if order_id is not numeric 
function1(['2774568',22,'aade'])

order_id = aade not valid.
order_id= 22 not present

   order_id                   products
0   2774568          21903 39190 47766
1        22  This order_id not present

In [136]:
#boundary case data_type not list
function1('akjf')

enter list of order_id

In [103]:
function1([1187899,12333333,329954])

order_id= 1233333333333333333 not present

              order_id                     products
0              1187899  196 10258 12427 25133 46149
1  1233333333333333333    This order_id not present
2               329954                         None

FUNCTION 2

In [141]:
data_train=pickle.load(open('/content/drive/MyDrive/instcart/DATA2/data_train.pkl','rb'))
print(data_train.shape)
data_train.head()

(8474661, 78)

                    up_unique_orders_count  ...  reordered
user_id product_id                          ...
1       196                             10  ...        1.0
        10258                            9  ...        1.0
        10326                            1  ...        0.0
        12427                           10  ...        0.0
        13032                            3  ...        1.0

[5 rows x 78 columns]

In [142]:
x=data_train.drop(['eval_set', 'order_id','reordered'], axis=1)
y=data_train.reordered
print(x.shape,y.shape)

(8474661, 75) (8474661,)

In [146]:
def function2(x,y):
    '''
    This function give F1-score for data_train
    '''
  model=pickle.load(open("/content/drive/MyDrive/instcart/DATA2/cat_clf_set2",'rb'))
  y_hat =(model.predict_proba(x)[:, 1] >= 0.21).astype('int')
  print("F1-score for data_train:", f1_score(y , y_hat))

In [147]:
function2(x,y)

F1-score for data_train: 0.4491083984866022